# Generated by Django 5.1rc1 on 2024-11-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedPlace',
        ),
    ]
